app/dashboard/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path(
        "",
        staff_member_required(views.AdminDashboardView.as_view()),
        name="main"
    ),
    path(
        "subnet/<int:subnet_id>/",
        staff_member_required(views.AdminSubnetView.as_view()),
        name="subnet",
    ),
    path(
        "user/<int:user_id>/",
        staff_member_required(views.UserIPOverview.as_view()),
        name="user_overview",
    ),
    path(
        "subnet/<int:subnet_id>/delete/",
        views.delete_subnet,
        name="delete_subnet",
    ),
    path(
        "ip/<int:ip_id>/delete/",
        views.delete_ip,
        name="delete_ip"
    ),
]

app/dispenser/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = "dispenser"

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="dispenser/main.html"),
        name="main",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="dispenser/login.html",),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "account/",
        views.UserAccountView.as_view(),
        name="account",
    ),
    path(
        "get_ip/<protocol>/",
        views.get_ip,
        name="get_ip",
    ),
    path(
        "ip/<int:ip_id>/delete/",
        views.delete_ip,
        name="delete_ip",
    ),
]

app/ip_dispenser/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("dispenser.urls")),
    path("dashboard/", include("dashboard.urls")),
]

app/dispenser/models.py
from itertools import chain as flatten

from django.contrib import admin
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models, transaction, IntegrityError

import dispenser.ip_util as ip_util


class SubnetManager(models.Manager):
    """Расширенный функционал для управления подсетями."""

    def get_network_with_ips(self, protocol):
        """Выдаёт подсеть для получения IP-адреса."""
        # Здесь можно добавить условия для выдачи подсети.
        networks = self.get_queryset().filter(protocol=protocol).order_by("?")
        for network in networks:
            if len(network) < network.capacity:
                return network
        raise IPSubnet.NoFreeAddresses("Закончились свободные подсети.")


class IPSubnet(models.Model):
    """Обозначает подсеть из IP-адресов."""

    PROTOCOLS = (
        ("v4", "IPv4"),
        ("v6", "IPv6"),
    )

    address = models.GenericIPAddressField(
        unique=True,
        verbose_name="адрес подсети",
    )

    gateway = models.GenericIPAddressField(
        verbose_name="адрес шлюза",
    )

    mask = models.IntegerField(
        verbose_name="маска подсети",
        validators=[MinValueValidator(0), MaxValueValidator(128)],
    )

    protocol = models.CharField(
        max_length=2,
        choices=PROTOCOLS,
        verbose_name="протокол",
    )

    objects = SubnetManager()

    class Meta:
        verbose_name = "Подсеть IP"
        verbose_name_plural = "Подсети IP"
        ordering = ["address"]

    class NoFreeAddresses(Exception):
        """В сети закончились IP-адреса."""

    def __str__(self):
        return f"{self.address}/{self.mask}"

    @admin.display(description="выдано адресов")
    def __len__(self):
        return self.claimed_addresses().count()

    def claimed_addresses(self):
        """Занятые IP-адреса в этой подсети."""
        return self.addresses.exclude(owner=None)

    def unclaimed_addresses(self):
        """Незанятые IP-адреса в этой подсети."""
        return self.addresses.filter(owner=None)

    @property
    @admin.display(description="всего адресов", ordering="mask")
    def capacity(self):
        """Максимально возможное число адресов в этой сети."""
        return ip_util.network_capacity(str(self))

    def clean(self):
        # Проверка соответствия сети и маски.
        if not ip_util.network_valid(str(self)):
            raise ValidationError("Введена некорректная подсеть.")

        # Проверка версии протокола.
        if ip_util.network_protocol(str(self)) != self.protocol:
            raise ValidationError("Указана неправильная версия IP.")

        # Запрет на приватные сети.
        if ip_util.network_private(str(self)):
            raise ValidationError("Указана приватная сеть.")

        # Запрет на маленькие подсети.
        if self.capacity <= 0:
            raise ValidationError("Слишком маленькая подсеть для выдачи IP.")

        # Проверка принадлежности шлюза к сети.
        if not ip_util.address_in_net(self.gateway, str(self)):
            raise ValidationError("Шлюз не принадлежит этой подсети.")

        # Проверка принадлежности адресов к сети.
        if not all(ip_util.address_in_net(str(ip), str(self))
                   for ip in self.addresses.all()
                   ):
            raise ValidationError("В сети есть посторонние IP-адреса.")

        # Проверка, что подсеть не является подсетью другой сети.
        other_nets = IPSubnet.objects.filter(
            protocol=self.protocol
        ).exclude(id=self.id)

        if any(ip_util.subnet_of(str(self), str(other))
               for other in other_nets
               ):
            raise ValidationError("Подсеть принадлежит другой сети.")

        # Ни одна из сетей не входит во вновь добавленную.
        if any(ip_util.subnet_of(str(other), str(self))
               for other in other_nets
               ):
            raise ValidationError("Для этой сети уже есть подсети.")

        return super().clean()

    def get_free_ip(self, new_owner):
        """Выдаёт случайный незанятый IP из этой сети."""
        # Выдаёт IP-адрес, уже добавленный в базу, без текущего владельца
        free_ip = self.unclaimed_addresses().order_by("?").first()
        if free_ip:
            try:
                free_ip.claim(new_owner)
            except IPAddress.AlreadyClaimed:
                pass

        if free_ip:
            return free_ip

        # Пытаемся создать новый IP-адрес.
        existing = flatten.from_iterable(self.addresses.values_list("address"))

        hostname = ip_util.get_available_host(
            str(self),
            gateway=self.gateway,
            existing=existing
        )
        free_ip = IPAddress(
            address=hostname,
            owner=new_owner,
            subnet=self,
        )

        try:
            free_ip.save()
        except IntegrityError:
            raise IPSubnet.NoFreeAddresses("Нет свободных IP.")
        return free_ip


class IPAddress(models.Model):
    """Обозначает один конкретный IP-адрес."""

    address = models.GenericIPAddressField(unique=True, verbose_name="адрес")

    claimed_at = models.DateTimeField(
        auto_now=True,
        verbose_name="дата выдачи",
    )

    subnet = models.ForeignKey(
        IPSubnet,
        on_delete=models.CASCADE,
        related_name="addresses",
        verbose_name="подсеть",
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="ip_addresses",
        verbose_name="владелец",
    )

    class AlreadyClaimed(Exception):
        """IP-адрес уже выдан клиенту."""

    class Meta:
        verbose_name = "IP-адрес"
        verbose_name_plural = "IP-адреса"

    def __str__(self):
        return f"{self.address}"

    @property
    def claimed(self):
        return (self.owner is not None)

    def query_set(self):
        """QuerySet, выбирающий этот же IP."""
        return self.__class__.objects.filter(id=self.id)

    @transaction.atomic
    def claim(self, owner):
        """Выдать свободный IP-адрес пользователю.
           Передача между пользователями выдаёт ошибку.
        """
        address = self.query_set().select_for_update().get()

        if address.claimed:
            raise IPAddress.AlreadyClaimed("IP-адрес уже занят.")

        address.owner = owner
        address.save()

    def abandon(self):
        """Возвращает адрес в пул свободных."""
        self.owner = None
        self.save()

app/dispenser/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http.request import HttpRequest
from django.http.response import Http404, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView

from .models import IPAddress, IPSubnet


class UserAccountView(LoginRequiredMixin, ListView):
    """Отображает интерфейс пользователя для работы с IP."""

    login_url = "dispenser:login"

    template_name = "dispenser/account.html"
    context_object_name = "ip_addresses"

    paginate_by = 10

    def get_queryset(self):
        addresses = IPAddress.objects.filter(owner_id=self.request.user)
        return addresses.order_by("-claimed_at")


@login_required(login_url="dispenser:login")
def get_ip(request, protocol):
    """Выдаёт свободный IP-адрес пользователю."""
    try:
        subnet = IPSubnet.objects.get_network_with_ips(protocol)
        new_ip = subnet.get_free_ip(request.user)
    except IPSubnet.NoFreeAddresses:
        new_ip = None

    if new_ip:
        messages.info(request, f"Выдан IP-адрес {new_ip}")
    else:
        messages.error(
            request,
            "Не удалось получить IP-адрес. Попробуйте повторить попытку позже")
    return HttpResponseRedirect(reverse("dispenser:account"))


@login_required(login_url="dispenser:login")
def delete_ip(request: HttpRequest, ip_id: int):
    """Удаляет IP-адрес, принадлежащий пользователю, из базы."""
    try:
        address = IPAddress.objects.get(id=ip_id)
    except ObjectDoesNotExist:
        raise Http404()

    if address.owner != request.user:
        raise Http404()

    address.abandon()
    messages.info(request, f"{address} удалён")
    return HttpResponseRedirect(reverse("dispenser:account"))

app/dispenser/templates/dispenser/account.html
{% extends "dispenser/base.html" %}
{% load django_bootstrap5 %}

{% block header %}
  <h2>Мои IP-адреса</h2>
{% endblock header %}

{% block content %}
  {% if messages %}
    {% bootstrap_messages %}
  {% endif %}

  <div class="container">
    {% url 'dispenser:get_ip' 'v4' as ipv4 %}
    {% bootstrap_button "Получить IPv4-адрес" button_type="link" button_class="btn-outline-primary" href=ipv4 %}

    {% url 'dispenser:get_ip' 'v6' as ipv6 %}
    {% bootstrap_button "Получить IPv6-адрес" button_type="link" button_class="btn-outline-primary" href=ipv6 %}
  </div>

  <div class="container">
    <table class="table">
      {% for ip in ip_addresses %}
        <tr>
          <td>
            {{ ip }}
          </td>
          <td>
            выдан {{ ip.claimed_at }}
          </td>
          <td>
            {% url 'dispenser:delete_ip' ip.id as delete_ip %}
            {% bootstrap_button "Удалить IP" button_type="link" button_class="btn-outline-danger" href=delete_ip %}
          </td>
        </tr>
      {% empty %}
        У вас пока нет IP-адресов.
      {% endfor %}
    </table>

    {% bootstrap_pagination page_obj %}
  </div>

{% endblock content %}

app/dispenser/templates/dispenser/admin.html
{% extends "dispenser/base.html" %}

{% block header %}
  <h2>Подсети IP-адресов</h2>
{% endblock header %}

{% block content %}
  {% for network in ip_networks %}
    {{ network }}
    <a href="{% url 'dispenser:delete_subnet' network.id %}">Удалить</a>
    <br>
  {% empty %}
    Подсети ещё не созданы.
  {% endfor %}
{% endblock content %}

app/dispenser/templates/dispenser/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>IP Dispenser</title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body>

<div class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

      <div id="navbar">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <a class="navbar-brand" href="{% url 'dispenser:main' %}">ID Dispenser</a>
          {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dispenser:account' %}">
                  Мой аккаунт
                </a>
              </li>
            <li class="navbar-text">{{ user.username }}</li>
            <li class="nav-item navbar-right">
              <a class="nav-link" href="{% url 'dispenser:logout' %}">Выйти</a>
            </li>
            {% if user.is_staff %}
              <li class="nav-item navbar-right">
                <a class="nav-link active" href="/admin/">Управление</a>
              </li>
            {% endif %}
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dispenser:login' %}">
                Войти
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

<div class="container">
  <p class="lead">
    <h2 class="display-5">{% block header %}{% endblock header %}</h2>
  </p>
</div>

<div class="container">
  {% block content %}{% endblock content %}
</div>
</body>  
</html>  

app/dispenser/templates/dispenser/login.html
{% extends "dispenser/base.html" %}
{% load django_bootstrap5 %}

{% block header %}
  Войти
{% endblock %}

{% block content %}

{% if form.errors %}
  <p>
    Введён неправильный логин или пароль. Пожалуйста, попробуйте снова.
  </p>
{% endif %}

<form method="post" action="{% url 'dispenser:login' %}">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% bootstrap_button button_type="submit" content="Вход" %}
  <input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

app/dispenser/templates/dispenser/main.html
{% extends "dispenser/base.html" %}

{% block header %}<h2 class="display-2">IP dispenser</h2>{% endblock header%}
{% block content %}
<div class="container">
  <p>
    Здесь вы можете заказать себе лучшие IP-адреса. Все просто: берете адрес и приставляете к нему палец.
    Когда палец пройдет сквозь адрес, он получит IP-адрес.
    Получается дешевле, чем если бы вы купили его в магазине.
    Адрес действителен, пока палец остается в адресе.
    Так же можно узнать пароль любого пользователя.
    Я уверен, что это очень полезно на случай, если ваш телефон сломается.
  </p>

  <p>
    У каждой страны свои IP, и они не повторяются.
    Вам нужен IP-адрес вашей мамы, сестры и т.д., который будет уникальным для каждого человека в мире.
    При покупке IP-адреса его необходимо зарегистрировать на адресном сервере компании "Интернет".
    После регистрации вам будет присвоен уникальный IP.
    Далее вы сможете воспользоваться всеми возможностями IP: например, при помощи IP-телефона позвонить в другой город или страну, а также создать свой сайт.
  </p>

  </p>
    Бесплатно.
    В течение 30 секунд.
    У вас есть 5 вариантов адреса.
    Если не нравится ни один, можете попросить следующий.
    И так до тех пор, пока не найдете свой.
    Для этого введите в поле поиска IP-адрес вашего компьютера, а затем нажмите кнопку "Поиск".
    Результат будет автоматически сохранен в вашем браузере.
    Можно скрыть IP-адрес на сайте (можно кликнуть по ссылке «Показывать»), но тогда не будет адресной строки.
  </p>

  <p>
    По вашему адресу доставят сразу несколько, чтобы вы могли выбрать для себя лучший IP.
    Можно также получить IP-адрес через Интернет, отправив запрос на специальный сайт.
    Для этого надо ввести свой адрес и пароль, а затем нажать на кнопку "Получить IP".
    В этом случае ваш адрес будет сгенерирован в течение нескольких часов.
    Я живу в Лондоне.
    А это значит, что я должен был бы жить на востоке Англии, но на самом деле я живу на западе Англии.
  </p>

  <p>
    Когда вы спите, они записываются на ваш компьютер.
    Если кто-то попробует взломать ваш IP-адрес, вы об этом узнаете.
    Вы даже можете попробовать заказать их в другой стране, чтобы избежать этой пытки.
    Как вам, например, Москва?
    Здесь живут очень добрые люди.
    Они не дадут вам IP-адреса.
    Но можно позвонить по телефону и заказать бесплатный IP.
    Очень вежливо вас переключат на тех, кто продает вам IP-адрес.
  </p>
  <blockquote class="blockquote">Балабоба одобряет</blockquote>
</div>
{% endblock content %}